#!/bin/bash

if [[ $# != 1 ]]; then
   echo "No commit name"
   exit 1
fi

git status
echo

if [[ $? != 0 ]]; then
    exit 1
fi

echo -n "Are you sure you want to push to github? (y/n) "
let answer
read answer
echo

if [[ $answer == "y" ]]; then
    git add .
    git commit -S -m "$1"
    git push
fi
